variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE
  IMAGE_TAG:  $CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  IMAGE: $IMAGE_NAME:$IMAGE_TAG

stages:
    - test
    - build
    - deploy

test:
  image: rust:1.59
  stage: test
  script:
    - cargo test

build:
  image: docker:19.03.12
  stage: build
  services:
    - docker:19.03.12-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE .
    - docker push $IMAGE

deploy:
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  stage: deploy
  before_script:
  - curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
  script:
  - kubectl config get-contexts
  - kubectl config use-context erigara-group/gitlab-agent:primary-agent
  - (cd ./manifests && kustomize edit set image IMAGE=$IMAGE)
  - kubectl apply -k ./manifests