---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: butler-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: butler-bot
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: butler-bot
    spec:
      imagePullSecrets:
      - name: gitlab-registry-credentials 
      containers:
      - image: IMAGE
        name: butler-bot
        env:
        - name: TELOXIDE_TOKEN
          valueFrom:
            secretKeyRef:
              name: butler-bot-secret
              key: teloxide-token
              optional: false
...